version: '3.8'

services:
  mcp:
    build:
      context: .
      dockerfile: Dockerfile
    image: graphrag-knowledge-mcp
    container_name: graphrag-knowledge-mcp
    volumes:
      - type: bind
        source: ~/.dra/docs
        target: /docs
    tty: true
    networks:
      - mcp_net
    depends_on:
      neo4j:
        condition: service_healthy

  rest-api:
    build:
      context: .
      dockerfile: Dockerfile.server
    image: graphrag-knowledge-rest-api
    container_name: graphrag-knowledge-rest-api
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=password
      - ALLOWED_ORIGINS=http://localhost:3000,http://localhost:3001
    networks:
      - mcp_net
    depends_on:
      neo4j:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3001/api/v1/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
  
  neo4j:
    image: neo4j:2025.02.0
    container_name: knowledge-neo4j
    environment:
      - NEO4J_AUTH=neo4j/password
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    volumes:
      - neo4j_data:/data
    networks:
      - mcp_net
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:7474 || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 30s

networks:
  mcp_net:
    driver: bridge

volumes:
  neo4j_data: